### tugas nomor 9 halaman 460 

sistem linier

\begin{equation*}
2x_1 − x_2 + x_3 = −1 \\
2x_1 + 2x_2 + 2x_3 = 4 \\
− x_1 −  x_2 + 2x_3 = −5
\end{equation*}

memiliki solusi 
\begin{equation*}
\left( 1,2,-1 \right)^t
\end{equation*}


#### 9.a.
tunjukan bahwa 
\begin{equation*} \rho\left( T_j \right) = \frac{\sqrt{5}}{2} \leq 1 \end{equation*}

diketahui bentuk dari 
\begin{equation*} T_j = D^{-1}\left( L+U \right) \end{equation*}

In [2]:
from numpy import linalg as LA
import numpy as np

masukkan bentuk persamaan diatas menjadi matriks

In [6]:
a9 = np.array([[2,-1,1],[2,2,2],[-1,-1,2]])
b9 = np.array([-1,4,5])

dicari matriks diagonal dan matriks selain diagonal pada matriks a9

In [4]:
d9 = np.diag(np.diag(a9))
c9 = a9 - d9
U9 = np.triu(a9,1)
L9 = np.tril(a9,-1)

maka didapat nilai Tj9 dan Cj9 yaitu

In [5]:
Tj9 = np.matmul(LA.inv(d9),c9)
Cj9 = np.matmul(LA.inv(d9),b9)
print(Tj9)
print(Cj9)

[[ 0.  -0.5  0.5]
 [ 1.   0.   1. ]
 [-0.5 -0.5  0. ]]
[-0.5  2.   2.5]


In [94]:
wtj9,vtj9 = LA.eig(Tj9)
abs(np.max(wtj9))

1.118033988749895

In [95]:
wcj9,vcj9 = LA.eig(np.diag(Cj9))
abs(np.max(wcj9))

2.5

### jacobi method

In [98]:
N9 = 25
x09 = np.array([0.0,0.0,0.0,0.0])
# x09 = np.array([0,100,100,100])
x_j9 = np.zeros((N9,len(x09)))
x_j9[0,:] = x09
e9 = 10^-6

for k in range(1,N9):
    for i in range(0,len(b9)):
        y = 0
        for j in range(0,len(b9)):
            if (j != i):
                y = y + a9[i,j]*x_j9[k-1,j]
                
        x_j9[k,i] = (1/a9[i,i]) * (b9[i]-y)

In [99]:
x_j9

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [ -0.5       ,   2.        ,   2.5       ,   0.        ],
       [ -0.75      ,   0.        ,   3.25      ,   0.        ],
       [ -2.125     ,  -0.5       ,   2.125     ,   0.        ],
       [ -1.8125    ,   2.        ,   1.1875    ,   0.        ],
       [ -0.09375   ,   2.625     ,   2.59375   ,   0.        ],
       [ -0.484375  ,  -0.5       ,   3.765625  ,   0.        ],
       [ -2.6328125 ,  -1.28125   ,   2.0078125 ,   0.        ],
       [ -2.14453125,   2.625     ,   0.54296875,   0.        ],
       [  0.54101562,   3.6015625 ,   2.74023438,   0.        ],
       [ -0.06933594,  -1.28125   ,   4.57128906,   0.        ],
       [ -3.42626953,  -2.50195312,   1.82470703,   0.        ],
       [ -2.66333008,   3.6015625 ,  -0.46411133,   0.        ],
       [  1.53283691,   5.12744141,   2.96911621,   0.        ],
       [  0.5791626 ,  -2.50195312,   5.83013916,   0.        ],
       [ -4.66604614,  -4

### Gauss-Seidel method

In [157]:
N9 = 25
x09 = np.array([0.0,0.0,0.0,0.0])
# x09 = np.array([0.0,100.0,100.0,100.0])
z = np.zeros((1,4))
x_gs9 = np.zeros((N9,len(x09)))
x_gs9[0,:] = x09
e9 = 10^-5

for k in range(1,N9):
    for i in range(0,len(b9)):
        y = 0
        for j in range(0,len(b9)):
            if (j != i):
                y = y + a9[i,j]*x09[j]
        
        x09[i] = (1/a9[i,i]) * (b9[i]-y)
    x_gs9[k,] = x09

In [158]:
 x_gs9

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.5       ,  2.5       ,  3.5       ,  0.        ],
       [-1.        , -0.5       ,  1.75      ,  0.        ],
       [-1.625     ,  1.875     ,  2.625     ,  0.        ],
       [-0.875     ,  0.25      ,  2.1875    ,  0.        ],
       [-1.46875   ,  1.28125   ,  2.40625   ,  0.        ],
       [-1.0625    ,  0.65625   ,  2.296875  ,  0.        ],
       [-1.3203125 ,  1.0234375 ,  2.3515625 ,  0.        ],
       [-1.1640625 ,  0.8125    ,  2.32421875,  0.        ],
       [-1.25585938,  0.93164062,  2.33789062,  0.        ],
       [-1.203125  ,  0.86523438,  2.33105469,  0.        ],
       [-1.23291016,  0.90185547,  2.33447266,  0.        ],
       [-1.21630859,  0.88183594,  2.33276367,  0.        ],
       [-1.22546387,  0.8927002 ,  2.33361816,  0.        ],
       [-1.22045898,  0.88684082,  2.33319092,  0.        ],
       [-1.22317505,  0.88998413,  2.33340454,  0.        ],
       [-1.22171021,  0.

### tugas nomor 10 halaman 460

sistem linier

\begin{equation*}
x_1 + 2x_2 - 2x_3 = 7 \\
x_1 + x_2 + x_3 = 2 \\
2x_1 +  2x_2 + x_3 = 5
\end{equation*}

memiliki solusi 
\begin{equation*}
\left( 1,2,-1 \right)^t
\end{equation*}


#### 10.a.
tunjukan bahwa 
\begin{equation*} \rho\left( T_j \right) = 0 \end{equation*}

In [163]:
a10 = np.array([[1,2,-2],[1,1,1],[2,2,1]])
b10 = np.array([7,2,5])

In [51]:
d10 = np.diag(np.diag(a10))
c10 = a10 - d10
U10 = np.triu(a10,1)
L10 = np.tril(a10,-1)

In [52]:
Tj10 = np.matmul(LA.inv(d10),c10)
Cj10 = np.matmul(LA.inv(d10),b10)
print(Tj10)
print(Cj10)

[[ 0.  2. -2.]
 [ 1.  0.  1.]
 [ 2.  2.  0.]]
[7. 2. 5.]


In [53]:
wtj10,vtj10 = LA.eig(Tj10)
abs(np.max(wtj10))

1.2333112361429784e-05

In [54]:
wcj10,vcj10 = LA.eig(np.diag(Cj10))
abs(np.max(wcj10))

7.0

### jacobi method

In [165]:
x_j10

array([[  0.,   0.,   0.,   0.],
       [  7.,   2.,   5.,   0.],
       [ 13., -10., -13.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.],
       [  1.,   2.,  -1.,   0.]])

### Gauss-Seidel method

In [166]:
N10 = 25
x010 = np.array([0.0,0.0,0.0,0.0])
# x09 = np.array([0,100,100,100])
x_gs10 = np.zeros((N10,len(x010)))
x_gs10[0,:] = x010
e10 = 10^-5

for k in range(1,N10):
    for i in range(0,len(b10)):
        y = 0
        for j in range(0,len(b10)):
            if (j != i):
                y = y + a10[i,j]*x010[j]
            
        x010[i] = (1/a10[i,i]) * (b10[i]-y)
    x_gs10[k,:] = x010

In [167]:
x_gs10

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 7.00000000e+00, -5.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 1.90000000e+01, -1.80000000e+01,  3.00000000e+00,
         0.00000000e+00],
       [ 4.90000000e+01, -5.00000000e+01,  7.00000000e+00,
         0.00000000e+00],
       [ 1.21000000e+02, -1.26000000e+02,  1.50000000e+01,
         0.00000000e+00],
       [ 2.89000000e+02, -3.02000000e+02,  3.10000000e+01,
         0.00000000e+00],
       [ 6.73000000e+02, -7.02000000e+02,  6.30000000e+01,
         0.00000000e+00],
       [ 1.53700000e+03, -1.59800000e+03,  1.27000000e+02,
         0.00000000e+00],
       [ 3.45700000e+03, -3.58200000e+03,  2.55000000e+02,
         0.00000000e+00],
       [ 7.68100000e+03, -7.93400000e+03,  5.11000000e+02,
         0.00000000e+00],
       [ 1.68970000e+04, -1.74060000e+04,  1.02300000e+03,
         0.00000000e+00],
       [ 3.68650000e+04, -3.78860000e+04,  2.04700000e+03,
      

### tugas nomor 11 halaman 460

sistem linier

\begin{equation*}
x_1 - x_3 = 0.2 \\
-0.5x_1 + x_2 - 0.25x_3 = -1.425 \\
x_1 - 0.5x_2 + x_3 = 2
\end{equation*}

memiliki solusi 
\begin{equation*}
\left( 0.9,-0.8,0.7 \right)^t
\end{equation*}

In [173]:
# a11 = np.array([[1,0,-1],[-0.5,1,-0.25],[1,-0.5,1]])
a11 = np.array([[1,0,-2],[-0.5,1,-0.25],[1,-0.5,1]])
b11 = np.array([0.2,-1.425,2])

 strictly diagonally dominant
 
 |1| = 0 + |-1| = 1
 |1| > |-0.5| + |-0.25| = 0.75
 |1| < |1| + |-0.5| = 1.5
 
 dari nilai diatas dapat disimpulkan bahwa matriks tersebut tidak strictly diagonally dominant

In [57]:
d11 = np.diag(np.diag(a11))
c11 = a10 - d11
U11 = np.triu(a11,1)
L11 = np.tril(a11,-1)

In [60]:
Tgs11 = np.matmul(-LA.inv(d11+L11),U11)
Cgs11 = np.matmul(LA.inv(d11+L11),b11)
print(Tgs11)
print(Cgs11)

[[ 0.     0.     1.   ]
 [ 0.     0.     0.75 ]
 [ 0.     0.    -0.625]]
[ 0.2    -1.325   1.1375]


In [61]:
wtgs11,vtgs11 = LA.eig(Tgs11)
abs(np.max(wtgs11))

0.0

In [62]:
wcgs11,vcgs11 = LA.eig(np.diag(Cgs11))
abs(np.max(wcgs11))

1.1375

### jacobi method

In [174]:
N11 = 25
x011 = np.array([0.0,0.0,0.0,0.0])
# x09 = np.array([0,100,100,100])
x_j11 = np.zeros((N11,len(x011)))
x_j11[0,:] = x011
e11 = 10^-6

for k in range(1,N11):
    for i in range(0,len(b11)):
        y = 0
        for j in range(0,len(b11)):
            if (j != i):
                y = y + a11[i,j]*x_j11[k-1,j]
                
        x_j11[k,i] = (1/a11[i,i]) * (b11[i]-y)

In [175]:
x_j11

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.00000000e-01, -1.42500000e+00,  2.00000000e+00,
         0.00000000e+00],
       [ 4.20000000e+00, -8.25000000e-01,  1.08750000e+00,
         0.00000000e+00],
       [ 2.37500000e+00,  9.46875000e-01, -2.61250000e+00,
         0.00000000e+00],
       [-5.02500000e+00, -8.90625000e-01,  9.84375000e-02,
         0.00000000e+00],
       [ 3.96875000e-01, -3.91289062e+00,  6.57968750e+00,
         0.00000000e+00],
       [ 1.33593750e+01,  4.18359375e-01, -3.53320313e-01,
         0.00000000e+00],
       [-5.06640625e-01,  5.16635742e+00, -1.11501953e+01,
         0.00000000e+00],
       [-2.21003906e+01, -4.46586914e+00,  5.08981934e+00,
         0.00000000e+00],
       [ 1.03796387e+01, -1.12027405e+01,  2.18674561e+01,
         0.00000000e+00],
       [ 4.39349121e+01,  9.23168335e+00, -1.39810089e+01,
         0.00000000e+00],
       [-2.77620178e+01,  1.70472038e+01, -3.73190704e+01,
      

### Gauss-Seidel method

In [176]:
N11 = 25
x011 = np.array([0.0,0.0,0.0,0.0])
# x09 = np.array([0,100,100,100])
x_gs11 = np.zeros((N11,len(x011)))
x_gs11[0,:] = x011
e11 = 10^-5

for k in range(1,N11):
    for i in range(0,len(b11)):
        y = 0
        for j in range(0,len(b11)):
            if (j != i):
                y = y + a11[i,j]*x011[j]
            
        x011[i] = (1/a11[i,i]) * (b11[i]-y)
    x_gs11[k,:] = x011

In [177]:
x_gs11

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.00000000e-01, -1.32500000e+00,  1.13750000e+00,
         0.00000000e+00],
       [ 2.47500000e+00,  9.68750000e-02, -4.26562500e-01,
         0.00000000e+00],
       [-6.53125000e-01, -1.85820313e+00,  1.72402344e+00,
         0.00000000e+00],
       [ 3.64804688e+00,  8.30029297e-01, -1.23303223e+00,
         0.00000000e+00],
       [-2.26606445e+00, -2.86629028e+00,  2.83291931e+00,
         0.00000000e+00],
       [ 5.86583862e+00,  2.21614914e+00, -2.75776405e+00,
         0.00000000e+00],
       [-5.31552811e+00, -4.77220507e+00,  4.92942557e+00,
         0.00000000e+00],
       [ 1.00588511e+01,  4.83678197e+00, -5.64046016e+00,
         0.00000000e+00],
       [-1.10809203e+01, -8.37557520e+00,  8.89313272e+00,
         0.00000000e+00],
       [ 1.79862654e+01,  9.79141591e+00, -1.10905575e+01,
         0.00000000e+00],
       [-2.19811150e+01, -1.51881969e+01,  1.63870166e+01,
      