In [13]:
from numpy import linalg as LA
import numpy as np

In [19]:
a = [[3,1,1,0],[1,5,-1,2],[1,0,3,1],[0,1,1,4]]
type(a)

list

In [22]:
print(LA.norm(a))
print(LA.norm(a,np.inf))
print(LA.norm(a,1))
print(LA.norm(a,2))

8.426149773176359
9.0
7.0
6.37996023668811


In [33]:
d = np.diag(np.diag(a))
c = a - d
c

array([[ 0,  1,  1,  0],
       [ 1,  0, -1,  2],
       [ 1,  0,  0,  1],
       [ 0,  1,  1,  0]])

In [40]:
b = np.matmul(-LA.inv(d),c)
b

array([[ 0.        , -0.33333333, -0.33333333,  0.        ],
       [-0.2       ,  0.        ,  0.2       , -0.4       ],
       [-0.33333333,  0.        ,  0.        , -0.33333333],
       [ 0.        , -0.25      , -0.25      ,  0.        ]])

In [42]:
w,v = LA.eig(b)

In [45]:
w

array([ 6.48878694e-01, -5.37344118e-01,  2.22589575e-17, -1.11534576e-01])